### PR TITLE
✨ Add Namespace Scoped Zone Discovery

### PR DESCRIPTION
**Pull request by chrischdi**
For testing:

- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3146

### CODE REVIEW

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-e2e-govmomi-conformance-main

Flake

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-e2e-vcsim-supervisor-main

Flake, it is green on the upstream PR

**Comment by chrischdi** [comment]
/test pull-cluster-api-provider-vsphere-e2e-vcsim-supervisor-main

Job got stuck

**Comment by sbueringer** [comment]
Somehow didn't detect that the upstream PR is merged

**Pull request closed without merging**
