### PR TITLE
✨ Add ability to add new data disks to VM during clone process

### PR DESCRIPTION
**Pull request by chrischdi**
Replicate for running e2e tests:

- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3214

### CODE REVIEW

**Comment by vr4manta** [comment]
Not sure why it fails against the vcenter we use for e2e.  Running this locally against out vcenter works.  Need to look more into why either the govmomi call to add addtional disks is failing or the call to get all devices / disks from the VM is not returning the new ones.

**Comment by vr4manta** [comment]
> > Not sure why it fails against the vcenter we use for e2e. Running this locally against our vcenter works. Need to look more into why either the govmomi call to add additional disks is failing or the call to get all devices / disks from the VM is not returning the new ones.
> 
> Failure is due to [kubernetes-sigs#3214 (comment)](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3214#discussion_r1856951098)

I made the change to pull the logic out and into its own block in the parent function.  Now it should run for all clone types.

**Comment by chrischdi** [comment]
/retest

(should be a unrelated flake

**Comment by chrischdi** [comment]
Let's run again:

/test pull-cluster-api-provider-vsphere-e2e-govmomi-blocking-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-conformance-ci-latest-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-conformance-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-main
/test pull-cluster-api-provider-vsphere-e2e-govmomi-upgrade-1-31-1-32-main

**Pull request closed without merging**
